# ----------------------------------------------------------------------------------------------------------------------
# Artemis MySQL Setup with PHPMyAdmin
# ----------------------------------------------------------------------------------------------------------------------

services:

    mysql:
        extends:
            file: ./mysql.yml
            service: mysql

    phpmyadmin:
        container_name: artemis-phpmyadmin
        image: phpmyadmin:latest 
        pull_policy: always

        ports:
            - "8081:80"
        expose:
            - "8081"

        links:
            - "mysql:db"

        networks:
            - artemis

networks:
    artemis:
        driver: "bridge"
        name: artemis
volumes:
    artemis-mysql-data:
        name: artemis-mysql-data
    artemis-data:
        name: artemis-data